# Generated by Django 5.2.14 on 2026-05-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamekey',
            options={'verbose_name': 'คีย์เกม', 'verbose_name_plural': 'คีย์เกมในคลัง'},
        ),
        migrations.AlterField(
            model_name='gamekey',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='เพิ่มเมื่อ'),
        ),
        migrations.AlterField(
            model_name='gamekey',
            name='is_sold',
            field=models.BooleanField(default=False, help_text='ติ๊กเมื่อคีย์ถูกใช้กับคำสั่งซื้อแล้ว (ระบบอาจอัปเดตให้อัตโนมัติ)', verbose_name='ขายแล้ว / จองแล้ว'),
        ),
        migrations.AlterField(
            model_name='gamekey',
            name='key_code',
            field=models.CharField(help_text='รหัสที่ลูกค้าใช้เปิดเกม (ต้องไม่ซ้ำกับคีย์อื่น)', max_length=255, unique=True, verbose_name='รหัสคีย์'),
        ),
    ]
