# Generated by Django 5.2.14 on 2026-05-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'เกม', 'verbose_name_plural': 'เกม'},
        ),
        migrations.AddField(
            model_name='game',
            name='detail_info',
            field=models.TextField(blank=True, default='', help_text='ข้อความยาว เช่น ระบบความต้องการ ฟีเจอร์ เนื้อเรื่อง — แสดงในหน้ารายละเอียดเกม', verbose_name='รายละเอียดเกม (หน้าเกม)'),
        ),
        migrations.AddField(
            model_name='game',
            name='key_usage_guide',
            field=models.TextField(blank=True, default='', help_text='ขั้นตอนเปิด Steam/Epic ฯลฯ — แสดงในหน้ารายละเอียดเกม', verbose_name='วิธีใช้คีย์ / แลกคีย์'),
        ),
        migrations.AlterField(
            model_name='game',
            name='cover_image_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL รูปปก'),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True, help_text='แสดงในหน้ารายการเกม / การ์ด', null=True, verbose_name='คำอธิบายสั้น (หน้าร้าน)'),
        ),
        migrations.AlterField(
            model_name='game',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='แสดงในร้าน'),
        ),
    ]
